### ISSUE TITLE
S3 storage

### ISSUE THREAD

**Issue by quentindemetz** [room118solutions/dynamic_paperclip#1]
What would it take to get this to work for S3 storage? Could you point me in the right direction?

**Comment by jimryan** [comment]
Dynamic Paperclip relies heavily on the idea that your HTTP server will serve the dynamically generated style if it exists, and pass the request along to the application if it doesn't.  Our middleware then catches that request and generates the style on-the-fly and returns it to the browser.  This allows the URL to remain unchanged - it's the same URL whether or not the style exists yet.  

I'm not sure how we would support S3 or any other cloud storage solution.  We could maybe get creative with the HTTP server configuration, and proxy requests to dynamically generated styles to the cloud service, returning the asset from the service if it exists, and if not, passing the request along to the application (similar to nginx's try_files). I'm not sure how performant that'd be, and you'd of course lose some of the benefits of S3 and the likes.  

I developed Dynamic Paperclip for one project, and we've since moved our other assets to a cloud solution.  I'm at a point now where I'm deciding if I should just drop Dynamic Paperclip and define the styles I need as I would normally, and generate and store them all upfront in the cloud with something like delayed_paperclip.  For me, Dynamic Paperclip can make a lot of sense if you need so many different styles that defining them upfront isn't acceptable, or if you don't know their dimensions upfront, but in situations where the number of styles are known, finite, and relatively low, and you want cloud storage, defining the styles upfront and delaying their generation is probably the best option. 

All of that said - if you can think of a reasonable way to make Dynamic Paperclip work with cloud storage solutions, I'd be very interested and would be happy to provide any guidance that I can on a PR.
